// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZGt_yYfG83euvCo1Wq69XXWK9CzPGo4',
    appId: '1:50047098344:web:0f323e2ebbd59daf96d85d',
    messagingSenderId: '50047098344',
    projectId: 'flutter-chat-app-90ebc',
    authDomain: 'flutter-chat-app-90ebc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-90ebc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2gqlTG-hOr3UtlEXSdtMH0W-Ox6DLunM',
    appId: '1:50047098344:android:b35278976f6225d596d85d',
    messagingSenderId: '50047098344',
    projectId: 'flutter-chat-app-90ebc',
    storageBucket: 'flutter-chat-app-90ebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-DbWIXWMA6KBloJgCRU45miFTdvCkCs',
    appId: '1:50047098344:ios:626ae6fe8c4f887996d85d',
    messagingSenderId: '50047098344',
    projectId: 'flutter-chat-app-90ebc',
    storageBucket: 'flutter-chat-app-90ebc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU-DbWIXWMA6KBloJgCRU45miFTdvCkCs',
    appId: '1:50047098344:ios:703c319ca9acf9fb96d85d',
    messagingSenderId: '50047098344',
    projectId: 'flutter-chat-app-90ebc',
    storageBucket: 'flutter-chat-app-90ebc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
